export const categories = [
  { id: 1, name: "Nhà Sách Tiki", icon: "/book-tiki-icon.jpg", slug: "nha-sach-tiki" },
  { id: 2, name: "Nhà Cửa - Đời Sống", icon: "/home-living-icon.jpg", slug: "nha-cua-doi-song" },
  { id: 3, name: "Điện Thoại - Máy Tính Bảng", icon: "/smartphone-tablet-icon.jpg", slug: "dien-thoai-may-tinh-bang" },
  { id: 4, name: "Đồ Chơi - Mẹ & Bé", icon: "/baby-toys-mother-icon.jpg", slug: "do-choi-me-be" },
  { id: 5, name: "Thiết Bị Số - Phụ Kiện Số", icon: "/headphones-digital-accessories-icon.jpg", slug: "thiet-bi-so-phu-kien-so" },
  { id: 6, name: "Điện Gia Dụng", icon: "/home-appliances-kettle-icon.jpg", slug: "dien-gia-dung" },
  { id: 7, name: "Làm Đẹp - Sức Khỏe", icon: "/beauty-health-cosmetics-icon.jpg", slug: "lam-dep-suc-khoe" },
  { id: 8, name: "Ô Tô - Xe Máy - Xe Đạp", icon: "/car-motorcycle-bicycle-icon.jpg", slug: "o-to-xe-may-xe-dap" },
  { id: 9, name: "Thời trang nữ", icon: "/women-fashion-dress-icon.jpg", slug: "thoi-trang-nu" },
  { id: 10, name: "Bách Hóa Online", icon: "/grocery-online-shopping-bag-icon.jpg", slug: "bach-hoa-online" },
  { id: 11, name: "Thể Thao - Dã Ngoại", icon: "/placeholder.svg?height=32&width=32", slug: "the-thao-da-ngoai" },
  { id: 12, name: "Thời trang nam", icon: "/placeholder.svg?height=32&width=32", slug: "thoi-trang-nam" },
  {
    id: 13,
    name: "Cross Border - Hàng Quốc Tế",
    icon: "/placeholder.svg?height=32&width=32",
    slug: "cross-border-hang-quoc-te",
  },
  {
    id: 14,
    name: "Laptop - Máy Vi Tính - Linh kiện",
    icon: "/placeholder.svg?height=32&width=32",
    slug: "laptop-may-vi-tinh-linh-kien",
  },
  { id: 15, name: "Giày - Dép nam", icon: "/placeholder.svg?height=32&width=32", slug: "giay-dep-nam" },
  { id: 16, name: "Điện Tử - Điện Lạnh", icon: "/placeholder.svg?height=32&width=32", slug: "dien-tu-dien-lanh" },
  { id: 17, name: "Giày - Dép nữ", icon: "/placeholder.svg?height=32&width=32", slug: "giay-dep-nu" },
  {
    id: 18,
    name: "Máy Ảnh - Máy Quay Phim",
    icon: "/placeholder.svg?height=32&width=32",
    slug: "may-anh-may-quay-phim",
  },
]

export const subCategories: Record<string, { id: number; name: string; slug: string }[]> = {
  "dien-gia-dung": [
    { id: 1, name: "Nồi điện các loại", slug: "noi-dien-cac-loai" },
    { id: 2, name: "Bếp các loại", slug: "bep-cac-loai" },
    { id: 3, name: "Máy hút khói, khử mùi", slug: "may-hut-khoi-khu-mui" },
    { id: 4, name: "Lò vi sóng", slug: "lo-vi-song" },
    { id: 5, name: "Lò nướng điện", slug: "lo-nuong-dien" },
    { id: 6, name: "Vỉ nướng điện", slug: "vi-nuong-dien" },
    { id: 7, name: "Máy xay, máy ép", slug: "may-xay-may-ep" },
    { id: 8, name: "Bình đun siêu tốc", slug: "binh-dun-sieu-toc" },
    { id: 9, name: "Bình thủy điện", slug: "binh-thuy-dien" },
    { id: 10, name: "Máy pha cà phê", slug: "may-pha-ca-phe" },
  ],
}

export const quickIcons = [
  { id: 1, name: "Deal Riêng", subtitle: "Giảm 50%", icon: "/placeholder.svg?height=44&width=44", color: "bg-white" },
  { id: 2, name: "Tiki Trading", subtitle: "", icon: "/placeholder.svg?height=44&width=44", color: "bg-white" },
  { id: 3, name: "Hot Coupon", subtitle: "Mỗi Ngày", icon: "/placeholder.svg?height=44&width=44", color: "bg-white" },
  {
    id: 4,
    name: "Noel Rộn Ràng",
    subtitle: "Giảm 50%",
    icon: "/placeholder.svg?height=44&width=44",
    color: "bg-white",
  },
  {
    id: 5,
    name: "Combo Nhà Dùng",
    subtitle: "Giảm 50%",
    icon: "/placeholder.svg?height=44&width=44",
    color: "bg-white",
  },
  { id: 6, name: "Tiki Rẻ Mỗi Ngày", subtitle: "", icon: "/placeholder.svg?height=44&width=44", color: "bg-white" },
  { id: 7, name: "Chăm Da Cuối Năm", subtitle: "", icon: "/placeholder.svg?height=44&width=44", color: "bg-white" },
  { id: 8, name: "Xả Kho Giá", subtitle: "Giảm 50%", icon: "/placeholder.svg?height=44&width=44", color: "bg-white" },
  { id: 9, name: "Tiệc Sách", subtitle: "Cuối Năm", icon: "/placeholder.svg?height=44&width=44", color: "bg-white" },
  { id: 10, name: "Điện Máy", subtitle: "Giảm 50%", icon: "/placeholder.svg?height=44&width=44", color: "bg-white" },
]

export const products = [
  {
    id: 1,
    name: "Nguyên Lý Marketing Phiên Bản Mới Nhất 2021 - Philip Kotler",
    slug: "nguyen-ly-marketing-phien-ban-moi-nhat-2021",
    price: 749200,
    originalPrice: 799200,
    discount: 6,
    rating: 4.8,
    reviewCount: 2147,
    soldCount: 9631,
    image: "/placeholder.svg?height=200&width=200",
    images: ["/placeholder.svg?height=400&width=400"],
    category: "nha-sach-tiki",
    brand: "NXB Trẻ",
    badges: ["TOP DEAL", "FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: false,
    deliveryTime: "Giao thứ 3, 23/12",
    description: "Sách Nguyên Lý Marketing phiên bản mới nhất",
    specifications: { weight: "500g", origin: "Việt Nam", storage: "", expiry: "" },
    features: ["Sách mới 100%", "Bản dịch chuẩn", "Giấy in chất lượng cao"],
    seller: { name: "Tiki Trading", isOfficial: true, rating: 4.7, reviewCount: 5500000 },
  },
  {
    id: 2,
    name: "Combo 2 cuốn sách hay về kinh tế: Quản Lý Khủng Hoảng - Philip Kotler",
    slug: "combo-2-cuon-sach-hay-ve-kinh-te",
    price: 177840,
    originalPrice: 222300,
    discount: 20,
    rating: 4.9,
    reviewCount: 1523,
    soldCount: 4521,
    image: "/placeholder.svg?height=200&width=200",
    images: ["/placeholder.svg?height=400&width=400"],
    category: "nha-sach-tiki",
    brand: "NXB Tổng Hợp",
    badges: ["TOP DEAL", "FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: false,
    deliveryTime: "Giao thứ 4, 24/12",
    description: "Combo sách kinh tế",
    specifications: { weight: "800g", origin: "Việt Nam", storage: "", expiry: "" },
    features: ["Combo 2 cuốn", "Sách mới 100%"],
    seller: { name: "Tiki Trading", isOfficial: true, rating: 4.8, reviewCount: 3200000 },
  },
  {
    id: 3,
    name: "Ghế chỉnh dáng ngồi đúng - Roichen Hàn Quốc (Made in Korea)",
    slug: "ghe-chinh-dang-ngoi-dung-roichen",
    price: 1432000,
    originalPrice: 1492000,
    discount: 4,
    rating: 4.7,
    reviewCount: 3241,
    soldCount: 12500,
    image: "/placeholder.svg?height=200&width=200",
    images: ["/placeholder.svg?height=400&width=400"],
    category: "nha-cua-doi-song",
    brand: "Roichen",
    badges: ["TOP DEAL", "FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: false,
    deliveryTime: "Giao chiều thứ 7, 20/12",
    origin: "Made in Korea",
    description: "Ghế chỉnh dáng ngồi đúng",
    specifications: { weight: "2kg", origin: "Hàn Quốc", storage: "", expiry: "" },
    features: ["Chính hãng Hàn Quốc", "Hỗ trợ cột sống"],
    seller: { name: "Roichen Official", isOfficial: true, rating: 4.6, reviewCount: 4100000 },
  },
  {
    id: 4,
    name: "Mặt nạ giấy dưỡng trắng da dừa leo Vedette Whitening sheet mask",
    slug: "mat-na-giay-duong-trang-da-vedette",
    price: 14280,
    originalPrice: 21000,
    discount: 32,
    rating: 5.0,
    reviewCount: 892,
    soldCount: 3200,
    image: "/placeholder.svg?height=200&width=200",
    images: ["/placeholder.svg?height=400&width=400"],
    category: "lam-dep-suc-khoe",
    brand: "Vedette",
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: false,
    deliveryTime: "Giao chủ nhật, 21/12",
    description: "Mặt nạ giấy dưỡng trắng da",
    specifications: { weight: "30g", origin: "Việt Nam", storage: "", expiry: "" },
    features: ["Dưỡng trắng da", "Cấp ẩm sâu"],
    seller: { name: "Vedette Official", isOfficial: true, rating: 4.5, reviewCount: 2800000 },
  },
  {
    id: 5,
    name: "Combo 3 Lay's Stax Khoai Tây Miếng Vị Thịt Nướng BBQ",
    slug: "combo-3-lays-stax-khoai-tay-vi-thit-nuong",
    price: 89760,
    originalPrice: 150000,
    discount: 40,
    rating: 4.7,
    reviewCount: 2549,
    soldCount: 8500,
    image: "/placeholder.svg?height=200&width=200",
    images: ["/placeholder.svg?height=400&width=400"],
    category: "bach-hoa-online",
    brand: "Lay's",
    badges: ["TOP DEAL", "FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: true,
    deliveryTime: "Giao siêu tốc 2h",
    description: "Combo snack khoai tây",
    specifications: { weight: "300g", origin: "Thái Lan", storage: "", expiry: "" },
    features: ["Combo tiết kiệm", "Vị BBQ thơm ngon"],
    seller: { name: "Tiki Trading", isOfficial: true, rating: 4.7, reviewCount: 3500000 },
  },
  {
    id: 6,
    name: "Trà Thìa canh Thái Hưng 25 túi lọc x 5g - Khắc tinh của đường",
    slug: "tra-thia-canh-thai-hung-25-tui-loc",
    price: 48000,
    originalPrice: 60000,
    discount: 20,
    rating: 4.5,
    reviewCount: 1876,
    soldCount: 15000,
    image: "/placeholder.svg?height=200&width=200",
    images: ["/placeholder.svg?height=400&width=400"],
    category: "bach-hoa-online",
    brand: "Thái Hưng",
    badges: ["TOP DEAL", "FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: false,
    deliveryTime: "Giao thứ 2, 22/12",
    description: "Trà thìa canh hỗ trợ tiểu đường",
    specifications: { weight: "125g", origin: "Việt Nam", storage: "", expiry: "" },
    features: ["25 túi lọc", "Hỗ trợ tiểu đường"],
    seller: { name: "Thái Hưng Official", isOfficial: true, rating: 4.7, reviewCount: 5500000 },
  },
  {
    id: 7,
    name: "Bình Đun Siêu Tốc 2 Lớp Lock&Lock EJK738BLK (1.7L) - Hàng Chính Hãng",
    slug: "binh-dun-sieu-toc-2-lop-locknlock-ejk738blk",
    price: 427000,
    originalPrice: 837000,
    discount: 49,
    rating: 4.7,
    reviewCount: 2147,
    soldCount: 9631,
    image: "/placeholder.svg?height=200&width=200",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "dien-gia-dung",
    brand: "LocknLock",
    badges: ["TOP DEAL", "FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: true,
    deliveryTime: "Giao siêu tốc 2h",
    description: "Ấm đun bằng thép không gỉ Lock&Lock, 1.7L màu đen EJK738BLK",
    specifications: {
      weight: "1.2 Kg",
      origin: "Trung Quốc",
      storage: "",
      expiry: "",
      capacity: "1.7L",
      power: "1800W",
      material: "Thép không gỉ, nhựa PP cao cấp",
    },
    features: [
      "Thiết kế hiện đại, sang trọng",
      "Công suất mạnh mẽ 1800W và nút bật màu đen sử dụng đơn giản",
      "Dung tích lớn 1.7L, đáp ứng nhiều nhu cầu sử dụng khác nhau",
    ],
    seller: { name: "Tiki Trading", isOfficial: true, rating: 4.7, reviewCount: 5500000 },
  },
  {
    id: 8,
    name: "Điện thoại ZTE V70 Design (8GB/128GB) - Hàng Chính Hãng",
    slug: "dien-thoai-zte-v70-design-8gb-128gb",
    price: 2290000,
    originalPrice: 2990000,
    discount: 23,
    rating: 4.6,
    reviewCount: 987,
    soldCount: 5600,
    image: "/placeholder.svg?height=200&width=200",
    images: ["/placeholder.svg?height=400&width=400"],
    category: "dien-thoai-may-tinh-bang",
    brand: "ZTE",
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: true,
    deliveryTime: "Giao siêu tốc 2h",
    description: "Điện thoại ZTE V70 Design",
    specifications: { weight: "180g", origin: "Trung Quốc", storage: "", expiry: "" },
    features: ["8GB RAM", "128GB ROM", "Màn hình AMOLED"],
    seller: { name: "Tiki Trading", isOfficial: true, rating: 4.7, reviewCount: 5500000 },
  },
]

export const featuredBrands = [
  {
    id: 1,
    name: "Apple",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Công nghệ ngập tràn",
    discount: "Giá giảm đến 50%",
  },
  {
    id: 2,
    name: "Nutifood",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Săn deal NutiFood",
    discount: "Giao nhanh 2H",
  },
  {
    id: 3,
    name: "Huggies",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Huggies giảm 100K",
    discount: "Mua tã tặng tã",
  },
  {
    id: 4,
    name: "TikiVIP",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Ngày hội TikiVIP 20.12",
    discount: "Deal khủng giảm 50%",
  },
  {
    id: 5,
    name: "Anlene",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Săn deal liền tay",
    discount: "Ưu đãi đến 35%",
  },
  {
    id: 6,
    name: "Hada Labo",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Gel rửa mặt",
    discount: "Mua 1 tặng 1",
  },
]

export const internationalProducts = [
  {
    id: 1,
    name: "Viên uống bổ mắt Lutein Rohto V5 (Hộp 30 viên)",
    price: 322050,
    originalPrice: 485000,
    discount: 34,
    rating: 5,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in Japan",
    nowDelivery: true,
    badges: ["TOP DEAL", "FREESHIP XTRA", "CHÍNH HÃNG"],
    seller: "TIKITRADING | Rohto",
  },
  {
    id: 2,
    name: "Sữa tắm gội cho bé Evoluderm 500ml",
    price: 135200,
    originalPrice: 190000,
    discount: 29,
    rating: 4,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in France",
    nowDelivery: false,
    deliveryTime: "Giao chiều mai",
    badges: ["CHÍNH HÃNG"],
    seller: "TIKITRADING | Evoluderm",
  },
  {
    id: 3,
    name: "Kem che khuyết điểm Aperire Daydream Cover",
    price: 149600,
    originalPrice: 329000,
    discount: 55,
    rating: 4,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in Korea",
    nowDelivery: true,
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    seller: "TIKITRADING | Aperire",
  },
  {
    id: 4,
    name: "Tinh Chất Cấp Ẩm Dạng Xịt 6 trong 1 Kirei JP",
    price: 349000,
    originalPrice: 399000,
    discount: 13,
    rating: 3.5,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in Japan",
    nowDelivery: false,
    deliveryTime: "Giao thứ 2, 22/12",
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    seller: "Hàng Chính Hãng",
  },
  {
    id: 5,
    name: "Phấn nước trang điểm dưỡng da GLAMRR Q LON",
    price: 325000,
    originalPrice: 525000,
    discount: 38,
    rating: 5,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in Korea",
    nowDelivery: false,
    deliveryTime: "Giao chiều mai",
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    seller: "TIKITRADING | GlamrrQ",
  },
  {
    id: 6,
    name: "Điện thoại Samsung Galaxy A36 5G (8GB/128GB)",
    price: 8240000,
    originalPrice: 8290000,
    discount: 1,
    rating: 4,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in Korea",
    nowDelivery: false,
    deliveryTime: "Giao chiều thứ 7, 20/12",
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    seller: "LONG HƯNG | SAMSUNG",
  },
]

export const reviews = [
  {
    id: 1,
    userId: "ĐN",
    userName: "Đào Nguyễn",
    memberYears: 7,
    reviewCount: 24,
    helpfulCount: 11,
    rating: 5,
    title: "Cực kì hài lòng",
    content:
      "tiếng kêu cũng vừa, k phải là nhỏ. đun đầy bình cỡ 5p. lúc vừa mở nắp ra có tí mùi nhe, sau đó hết. dùng gần 2 tuần rồi thấy ổn cả nhe. nắp hơi khó mở, nhỡ mà gãy phần đó là nghỉ mở lun😅",
    isPurchased: true,
    variant: "Đen",
    date: "4 năm trước",
    usageDays: 14,
    images: [
      "/placeholder.svg?height=80&width=80",
      "/placeholder.svg?height=80&width=80",
      "/placeholder.svg?height=80&width=80",
      "/placeholder.svg?height=80&width=80",
      "/placeholder.svg?height=80&width=80",
    ],
    likes: 7,
    comments: 1,
  },
]

export const formatPrice = (price: number) => {
  return new Intl.NumberFormat("vi-VN").format(price) + "đ"
}

export const banners = [
  {
    id: 1,
    title: "GIÁNG SINH RỘN RÀNG",
    subtitle: "SALE SẬP SÀN",
    image: "/placeholder.svg?height=380&width=700",
    link: "/category/giang-sinh",
    badges: ["TRẢ GÓP 0%", "GIẢM ĐẾN 50%", "GIAO NHANH 2H"],
  },
  {
    id: 2,
    title: "Gia dụng siêu deal",
    subtitle: "Giáng sinh siêu sale",
    image: "/placeholder.svg?height=380&width=400",
    link: "/category/nha-cua-doi-song",
    badges: ["Giảm đến 50%", "Giao nhanh 2H"],
    isSecondary: true,
  },
]
