export const categories = [
  { id: 1, name: "NGON", icon: "/book-tiki-icon.jpg", slug: "ngon" },
  {
    id: 2,
    name: "Thực Phẩm Tươi Sống",
    icon: "/home-living-icon.jpg",
    slug: "thuc-pham-tuoi-song",
  },
  {
    id: 3,
    name: "Cá, Thuỷ Hải Sản",
    icon: "/smartphone-tablet-icon.jpg",
    slug: "ca-thuy-hai-san",
  },
  {
    id: 4,
    name: "Thịt, Trứng",
    icon: "/baby-toys-mother-icon.jpg",
    slug: "thit-trung",
  },
  {
    id: 5,
    name: "Rau, Củ, Trái Cây",
    icon: "/headphones-digital-accessories-icon.jpg",
    slug: "rau-cu-trai-cay",
  },
  {
    id: 6,
    name: "Đồ Khô, Gia Vị",
    icon: "/home-appliances-kettle-icon.jpg",
    slug: "do-kho-gia-vi",
  },
  {
    id: 7,
    name: "Đồ Ăn Vặt",
    icon: "/beauty-health-cosmetics-icon.jpg",
    slug: "do-an-vat",
  },
  {
    id: 8,
    name: "Sữa, Bơ, Phô Mai",
    icon: "/car-motorcycle-bicycle-icon.jpg",
    slug: "sua-bo-pho-mai",
  },
  {
    id: 9,
    name: "Nước, Giải Khát",
    icon: "/women-fashion-dress-icon.jpg",
    slug: "nuoc-giai-khat",
  },
  {
    id: 10,
    name: "Bánh Kẹo, Chocolate",
    icon: "/grocery-online-shopping-bag-icon.jpg",
    slug: "banh-keo-chocolate",
  },
  {
    id: 11,
    name: "Đồ Uống Có Cồn",
    icon: "/placeholder.svg?height=32&width=32",
    slug: "do-uong-co-con",
  },
  {
    id: 12,
    name: "Chăm Sóc Cá Nhân",
    icon: "/placeholder.svg?height=32&width=32",
    slug: "cham-soc-ca-nhan",
  },
  {
    id: 13,
    name: "Chăm Sóc Nhà Cửa",
    icon: "/placeholder.svg?height=32&width=32",
    slug: "cham-soc-nha-cua",
  },
  {
    id: 14,
    name: "Đồ Dùng Gia Đình",
    icon: "/placeholder.svg?height=32&width=32",
    slug: "do-dung-gia-dinh",
  },
  {
    id: 15,
    name: "Mẹ & Bé",
    icon: "/placeholder.svg?height=32&width=32",
    slug: "me-be",
  },
  {
    id: 16,
    name: "Điện Gia Dụng",
    icon: "/placeholder.svg?height=32&width=32",
    slug: "dien-gia-dung",
  },
  {
    id: 17,
    name: "Thú Cưng",
    icon: "/placeholder.svg?height=32&width=32",
    slug: "thu-cung",
  },
  {
    id: 18,
    name: "Thời Trang & Làm Đẹp",
    icon: "/placeholder.svg?height=32&width=32",
    slug: "thoi-trang-lam-dep",
  },
];

export const subCategories: Record<
  string,
  { id: number; name: string; slug: string }[]
> = {
  "ca-thuy-hai-san": [
    { id: 1, name: "Tôm, Cua, Ghẹ, Ốc", slug: "tom-cua-ghe-oc" },
    { id: 2, name: "Tôm", slug: "tom" },
    { id: 3, name: "Cua, Ghẹ", slug: "cua-ghe" },
    { id: 4, name: "Ốc", slug: "oc" },
    { id: 5, name: "Cá Tươi Sống", slug: "ca-tuoi-song" },
    { id: 6, name: "Hải Sản Tươi", slug: "hai-san-tuoi" },
    { id: 7, name: "Mực, Bạch Tuộc", slug: "muc-bach-tuoc" },
    { id: 8, name: "Tôm Hùm", slug: "tom-hum" },
    { id: 9, name: "Hải Sản Đông Lạnh", slug: "hai-san-dong-lanh" },
    { id: 10, name: "Các Loại Khác", slug: "cac-loai-khac" },
  ],
  "thit-trung": [
    { id: 1, name: "Thịt Heo", slug: "thit-heo" },
    { id: 2, name: "Thịt Bò", slug: "thit-bo" },
    { id: 3, name: "Thịt Gà", slug: "thit-ga" },
    { id: 4, name: "Thịt Vịt", slug: "thit-vit" },
    { id: 5, name: "Trứng", slug: "trung" },
    { id: 6, name: "Thịt Đông Lạnh", slug: "thit-dong-lanh" },
  ],
};

export const quickIcons = [
  {
    id: 1,
    name: "Deal Sốc",
    subtitle: "Giảm 50%",
    icon: "/placeholder.svg?height=44&width=44",
    color: "bg-white",
  },
  {
    id: 2,
    name: "Freeship",
    subtitle: "Mỗi Ngày",
    icon: "/placeholder.svg?height=44&width=44",
    color: "bg-white",
  },
  {
    id: 3,
    name: "Hot Deal",
    subtitle: "Hôm Nay",
    icon: "/placeholder.svg?height=44&width=44",
    color: "bg-white",
  },
  {
    id: 4,
    name: "Tươi Ngon",
    subtitle: "Giảm 30%",
    icon: "/placeholder.svg?height=44&width=44",
    color: "bg-white",
  },
  {
    id: 5,
    name: "Combo Tiết Kiệm",
    subtitle: "Giảm 40%",
    icon: "/placeholder.svg?height=44&width=44",
    color: "bg-white",
  },
  {
    id: 6,
    name: "Flash Sale",
    subtitle: "2H",
    icon: "/placeholder.svg?height=44&width=44",
    color: "bg-white",
  },
  {
    id: 7,
    name: "Hải Sản Tươi",
    subtitle: "Mới Về",
    icon: "/placeholder.svg?height=44&width=44",
    color: "bg-white",
  },
  {
    id: 8,
    name: "Thịt Nhập Khẩu",
    subtitle: "Giảm 50%",
    icon: "/placeholder.svg?height=44&width=44",
    color: "bg-white",
  },
  {
    id: 9,
    name: "Rau Củ Sạch",
    subtitle: "An Toàn",
    icon: "/placeholder.svg?height=44&width=44",
    color: "bg-white",
  },
  {
    id: 10,
    name: "Đông Lạnh",
    subtitle: "Giữ Tươi",
    icon: "/placeholder.svg?height=44&width=44",
    color: "bg-white",
  },
];

export const products = [
  {
    id: 1,
    name: "Tôm hùm Canada (Alaska) sống size 500g",
    slug: "tom-hum-canada-alaska-song-size-500g",
    price: 448000,
    originalPrice: 498000,
    discount: 10,
    rating: 5.0,
    reviewCount: 4,
    soldCount: 23,
    image: "/live-lobster-on-ice.jpg",
    images: [
      "/live-lobster-on-ice.jpg",
      "/lobster-close-up-detail.jpg",
      "/lobster-packaging-box.jpg",
      "/lobster-on-plate-garnished.jpg",
    ],
    category: "ca-thuy-hai-san",
    brand: "Maya",
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: false,
    deliveryTime: "Giao thứ 3, 23/12",
    description:
      "Tôm hùm Canada (Alaska) sống tươi, size 500g. Đảm bảo chất lượng tươi ngon, được bảo quản lạnh đạt chuẩn.",
    specifications: {
      weight: "500g",
      origin: "Canada",
      storage: "Bảo quản lạnh -18°C",
      expiry: "6 tháng kể từ ngày sản xuất",
    },
    features: [
      "Tôm hùm nhập khẩu chính hãng từ Canada",
      "Đảm bảo tươi sống 100%",
      "Đóng gói kín đáo, vệ sinh",
      "Giàu dinh dưỡng, protein cao",
      "Phù hợp chế biến nhiều món ăn",
    ],
    seller: {
      name: "Maya Seafood",
      isOfficial: true,
      rating: 5.0,
      reviewCount: 8,
    },
  },
  {
    id: 2,
    name: "Tôm Hùm Bông Đông Lạnh - 1 Con 500g [GIAO NHANH HCM]",
    slug: "tom-hum-bong-dong-lanh-500g",
    price: 561000,
    originalPrice: 650000,
    discount: 14,
    rating: 4.8,
    reviewCount: 12,
    soldCount: 45,
    image: "/frozen-lobster-crab-seafood.jpg",
    images: ["/frozen-lobster-crab-seafood.jpg", "/lobster-cooked-dish.jpg"],
    category: "ca-thuy-hai-san",
    brand: "Fresh Mart",
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: true,
    deliveryTime: "Giao siêu tốc 2h",
    description: "Tôm hùm bông đông lạnh, thịt chắc, ngọt tự nhiên",
    specifications: {
      weight: "500g",
      origin: "Việt Nam",
      storage: "Bảo quản đông lạnh -18°C",
      expiry: "12 tháng",
    },
    features: [
      "Tôm hùm bông tươi đông lạnh",
      "Chất lượng cao",
      "Giao nhanh HCM",
    ],
    seller: {
      name: "Fresh Mart Official",
      isOfficial: true,
      rating: 4.7,
      reviewCount: 150,
    },
  },
  {
    id: 3,
    name: "Tôm Hùm Baby Canada Hấp - 1 Con [GIAO NHANH HCM]",
    slug: "tom-hum-baby-canada-hap",
    price: 365000,
    originalPrice: 420000,
    discount: 13,
    rating: 4.9,
    reviewCount: 8,
    soldCount: 30,
    image: "/cooked-shrimp-platter.png",
    images: ["/cooked-shrimp-platter.png", "/lobster-on-plate-garnished.jpg"],
    category: "ca-thuy-hai-san",
    brand: "Maya",
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: true,
    deliveryTime: "Giao siêu tốc 2h",
    description: "Tôm hùm baby Canada đã hấp chín sẵn, tiện lợi",
    specifications: {
      weight: "200-300g/con",
      origin: "Canada",
      storage: "Bảo quản lạnh 0-4°C",
      expiry: "3 ngày",
    },
    features: [
      "Tôm hùm baby Canada",
      "Đã hấp chín sẵn",
      "Siêu tiện lợi",
      "Giao nhanh HCM",
    ],
    seller: {
      name: "Maya Seafood",
      isOfficial: true,
      rating: 5.0,
      reviewCount: 8,
    },
  },
  {
    id: 4,
    name: "Tôm hùm Canada (Alaska) sống size 500g",
    slug: "tom-hum-canada-alaska-song-size-500g",
    price: 448000,
    originalPrice: 498000,
    discount: 10,
    rating: 5.0,
    reviewCount: 4,
    soldCount: 23,
    image: "/live-lobster-on-ice.jpg",
    images: [
      "/live-lobster-on-ice.jpg",
      "/lobster-close-up-detail.jpg",
      "/lobster-packaging-box.jpg",
      "/lobster-on-plate-garnished.jpg",
    ],
    category: "ca-thuy-hai-san",
    brand: "Maya",
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: false,
    deliveryTime: "Giao thứ 3, 23/12",
    description:
      "Tôm hùm Canada (Alaska) sống tươi, size 500g. Đảm bảo chất lượng tươi ngon, được bảo quản lạnh đạt chuẩn.",
    specifications: {
      weight: "500g",
      origin: "Canada",
      storage: "Bảo quản lạnh -18°C",
      expiry: "6 tháng kể từ ngày sản xuất",
    },
    features: [
      "Tôm hùm nhập khẩu chính hãng từ Canada",
      "Đảm bảo tươi sống 100%",
      "Đóng gói kín đáo, vệ sinh",
      "Giàu dinh dưỡng, protein cao",
      "Phù hợp chế biến nhiều món ăn",
    ],
    seller: {
      name: "Maya Seafood",
      isOfficial: true,
      rating: 5.0,
      reviewCount: 8,
    },
  },
  {
    id: 5,
    name: "Tôm hùm Canada (Alaska) sống size 500g",
    slug: "tom-hum-canada-alaska-song-size-500g",
    price: 448000,
    originalPrice: 498000,
    discount: 10,
    rating: 5.0,
    reviewCount: 4,
    soldCount: 23,
    image: "/live-lobster-on-ice.jpg",
    images: [
      "/live-lobster-on-ice.jpg",
      "/lobster-close-up-detail.jpg",
      "/lobster-packaging-box.jpg",
      "/lobster-on-plate-garnished.jpg",
    ],
    category: "ca-thuy-hai-san",
    brand: "Maya",
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: false,
    deliveryTime: "Giao thứ 3, 23/12",
    description:
      "Tôm hùm Canada (Alaska) sống tươi, size 500g. Đảm bảo chất lượng tươi ngon, được bảo quản lạnh đạt chuẩn.",
    specifications: {
      weight: "500g",
      origin: "Canada",
      storage: "Bảo quản lạnh -18°C",
      expiry: "6 tháng kể từ ngày sản xuất",
    },
    features: [
      "Tôm hùm nhập khẩu chính hãng từ Canada",
      "Đảm bảo tươi sống 100%",
      "Đóng gói kín đáo, vệ sinh",
      "Giàu dinh dưỡng, protein cao",
      "Phù hợp chế biến nhiều món ăn",
    ],
    seller: {
      name: "Maya Seafood",
      isOfficial: true,
      rating: 5.0,
      reviewCount: 8,
    },
  },
  {
    id: 6,
    name: "Cá Hồi Na Uy Fillet Phi Lê - Khay 500g",
    slug: "ca-hoi-na-uy-fillet-phi-le-500g",
    price: 295000,
    originalPrice: 350000,
    discount: 16,
    rating: 4.9,
    reviewCount: 234,
    soldCount: 678,
    image: "/salmon-fillet-sliced.jpg",
    images: [
      "/salmon-fillet-sliced.jpg",
      "/fresh-salmon-fish-whole.jpg",
      "/salmon-sashimi-plate.jpg",
      "/pan-seared-salmon.png",
    ],
    category: "ca-thuy-hai-san",
    brand: "Ocean Fresh",
    badges: ["TOP DEAL", "FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: true,
    deliveryTime: "Giao siêu tốc 2h",
    description: "Cá hồi Na Uy phi lê không xương, tươi ngon, giàu Omega-3",
    specifications: {
      weight: "500g",
      origin: "Na Uy",
      storage: "Bảo quản đông lạnh -18°C",
      expiry: "12 tháng",
    },
    features: [
      "Cá hồi Na Uy nhập khẩu",
      "Phi lê không xương",
      "Giàu Omega-3",
      "Chất lượng cao",
      "Đóng gói vệ sinh",
    ],
    seller: {
      name: "Ocean Fresh Official",
      isOfficial: true,
      rating: 4.9,
      reviewCount: 450,
    },
  },
  {
    id: 7,
    name: "Tôm Sú Đông Lạnh Bỏ Đầu - Hộp 1kg",
    slug: "tom-su-dong-lanh-bo-dau-1kg",
    price: 385000,
    originalPrice: 450000,
    discount: 14,
    rating: 4.7,
    reviewCount: 89,
    soldCount: 267,
    image: "/tiger-prawns-fresh.jpg",
    images: ["/tiger-prawns-fresh.jpg", "/tiger-shrimp.jpg"],
    category: "ca-thuy-hai-san",
    brand: "Sea Food",
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: false,
    deliveryTime: "Giao thứ 3, 23/12",
    description: "Tôm sú tươi đông lạnh, bỏ đầu sẵn, tiện lợi",
    specifications: {
      weight: "1kg",
      origin: "Việt Nam",
      storage: "Bảo quản đông lạnh -18°C",
      expiry: "12 tháng",
    },
    features: ["Tôm sú size to", "Bỏ đầu sẵn", "Tươi ngon", "Tiện chế biến"],
    seller: {
      name: "Sea Food Official",
      isOfficial: true,
      rating: 4.7,
      reviewCount: 180,
    },
  },
  {
    id: 8,
    name: "Mực Ống Đông Lạnh Làm Sạch - Gói 500g",
    slug: "muc-ong-dong-lanh-lam-sach-500g",
    price: 145000,
    originalPrice: 180000,
    discount: 19,
    rating: 4.8,
    reviewCount: 67,
    soldCount: 198,
    image: "/cleaned-squid.jpg",
    images: [
      "/cleaned-squid.jpg",
      "/fresh-squid-seafood.jpg",
      "/squid-octopus.jpg",
    ],
    category: "ca-thuy-hai-san",
    brand: "Sea Food",
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    nowDelivery: true,
    deliveryTime: "Giao siêu tốc 2h",
    description: "Mực ống tươi đông lạnh, làm sạch sẵn",
    specifications: {
      weight: "500g",
      origin: "Việt Nam",
      storage: "Bảo quản đông lạnh -18°C",
      expiry: "12 tháng",
    },
    features: ["Mực ống tươi", "Làm sạch sẵn", "Tiện chế biến", "Giá tốt"],
    seller: {
      name: "Sea Food Official",
      isOfficial: true,
      rating: 4.7,
      reviewCount: 180,
    },
  },
];

export const featuredBrands = [
  {
    id: 1,
    name: "Thực Phẩm Tươi",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Tươi ngon mỗi ngày",
    discount: "Giá giảm đến 30%",
  },
  {
    id: 2,
    name: "Hải Sản Cao Cấp",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Nhập khẩu chính hãng",
    discount: "Giao nhanh 2H",
  },
  {
    id: 3,
    name: "Thịt Nhập Khẩu",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "US Beef giảm 100K",
    discount: "Mua nhiều giảm sâu",
  },
  {
    id: 4,
    name: "Flash Sale",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Flash Sale Mỗi Ngày",
    discount: "Deal khủng giảm 50%",
  },
  {
    id: 5,
    name: "Rau Củ Organic",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Sạch & An toàn",
    discount: "Ưu đãi đến 25%",
  },
  {
    id: 6,
    name: "Combo Tiết Kiệm",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Combo gia đình",
    discount: "Mua 1 tặng 1",
  },
];

export const internationalProducts = [
  {
    id: 1,
    name: "Tôm Hùm Canada Size Jumbo 1kg",
    price: 1210000,
    originalPrice: 1450000,
    discount: 17,
    rating: 5,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in Canada",
    nowDelivery: true,
    badges: ["TOP DEAL", "FREESHIP XTRA", "CHÍNH HÃNG"],
    seller: "Maya Seafood",
  },
  {
    id: 2,
    name: "Cá Hồi Na Uy Fillet Phi Lê Premium 1kg",
    price: 580000,
    originalPrice: 720000,
    discount: 19,
    rating: 5,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in Norway",
    nowDelivery: true,
    deliveryTime: "Giao siêu tốc 2h",
    badges: ["CHÍNH HÃNG"],
    seller: "Ocean Fresh",
  },
  {
    id: 3,
    name: "Bạch Tuộc Nhật Bản Sashimi 500g",
    price: 380000,
    originalPrice: 480000,
    discount: 21,
    rating: 4.9,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in Japan",
    nowDelivery: true,
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    seller: "Sushi Master",
  },
  {
    id: 4,
    name: "Thịt Bò Wagyu Nhật Bản A5 - 300g",
    price: 1850000,
    originalPrice: 2100000,
    discount: 12,
    rating: 5,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in Japan",
    nowDelivery: false,
    deliveryTime: "Giao thứ 3, 23/12",
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    seller: "Premium Meat",
  },
  {
    id: 5,
    name: "Cua Hoàng Đế Alaska Size Lớn 2kg",
    price: 2650000,
    originalPrice: 3200000,
    discount: 17,
    rating: 5,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in USA",
    nowDelivery: false,
    deliveryTime: "Giao thứ 4, 24/12",
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    seller: "Premium Seafood",
  },
  {
    id: 6,
    name: "Sò Điệp Canada Tươi Đông Lạnh 500g",
    price: 285000,
    originalPrice: 350000,
    discount: 19,
    rating: 4.8,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in Canada",
    nowDelivery: false,
    deliveryTime: "Giao thứ 3, 23/12",
    badges: ["FREESHIP XTRA", "CHÍNH HÃNG"],
    seller: "Sea Delights",
  },
];

export const reviews = [
  {
    id: 1,
    userId: "NT",
    userName: "Nguyễn Thảo",
    memberYears: 5,
    reviewCount: 18,
    helpfulCount: 9,
    rating: 5,
    title: "Tôm hùm tươi ngon",
    content:
      "Tôm hùm rất tươi, còn sống khi nhận hàng. Đóng gói cẩn thận, có đá khô bảo quản. Thịt chắc, ngọt tự nhiên. Nấu lẩu rất ngon. Sẽ ủng hộ shop lâu dài.",
    isPurchased: true,
    variant: "500g",
    date: "2 tuần trước",
    usageDays: 1,
    images: [
      "/live-lobster-on-ice.jpg",
      "/lobster-close-up-detail.jpg",
      "/lobster-packaging-box.jpg",
    ],
    likes: 12,
    comments: 2,
  },
  {
    id: 2,
    userId: "HM",
    userName: "Hoàng Minh",
    memberYears: 3,
    reviewCount: 8,
    helpfulCount: 5,
    rating: 5,
    title: "Chất lượng tuyệt vời",
    content:
      "Lần đầu mua hải sản online, ban đầu hơi lo lắng nhưng khi nhận hàng thì thấy rất hài lòng. Tôm hùm tươi, size chuẩn như mô tả. Giao hàng nhanh, đóng gói kỹ lưỡng.",
    isPurchased: true,
    variant: "500g",
    date: "1 tháng trước",
    usageDays: 1,
    images: ["/lobster-cooked-dish.jpg", "/lobster-on-plate-garnished.jpg"],
    likes: 8,
    comments: 1,
  },
];

export const formatPrice = (price: number) => {
  return new Intl.NumberFormat("vi-VN").format(price) + "đ";
};

export const banners = [
  {
    id: 1,
    title: "THỰC PHẨM ĐÔNG LẠNH",
    subtitle: "TƯƠI NGON - AN TOÀN",
    image: "/banner1.png",
    link: "/category/ca-thuy-hai-san",
    badges: ["TRẢ GÓP 0%", "GIẢM ĐẾN 30%", "GIAO NHANH 2H"],
  },
  {
    id: 2,
    title: "Hải sản nhập khẩu",
    subtitle: "Chất lượng cao",
    image: "/banner2.png",
    link: "/category/ca-thuy-hai-san",
    badges: ["Giảm đến 25%", "Giao nhanh 2H"],
    isSecondary: true,
  },
];
