export const categories = [
  {
    id: 1,
    name: "Xi Măng & Vữa",
    icon: "🏭",
    color: "#0b74e5",
    slug: "xi-mang-vua",
  },
  {
    id: 2,
    name: "Gạch Xây & Ốp Lát",
    icon: "🧱",
    color: "#ff424e",
    slug: "gach-xay-op-lat",
  },
  {
    id: 3,
    name: "Sơn & Chống Thấm",
    icon: "🎨",
    color: "#0b74e5",
    slug: "son-chong-tham",
  },
  {
    id: 4,
    name: "Thép Xây Dựng",
    icon: "🔩",
    color: "#ff424e",
    slug: "thep-xay-dung",
  },
  {
    id: 5,
    name: "Ống Nước & Phụ Kiện",
    icon: "💧",
    color: "#0b74e5",
    slug: "ong-nuoc-phu-kien",
  },
  {
    id: 6,
    name: "Điện & Đèn Chiếu Sáng",
    icon: "💡",
    color: "#ffa500",
    slug: "dien-den-chieu-sang",
  },
  {
    id: 7,
    name: "Công Cụ Xây Dựng",
    icon: "🔨",
    color: "#ff424e",
    slug: "cong-cu-xay-dung",
  },
  {
    id: 8,
    name: "Cửa & Cửa Sổ",
    icon: "🚪",
    color: "#0b74e5",
    slug: "cua-cua-so",
  },
  {
    id: 9,
    name: "Ngói & Lợp Mái",
    icon: "🏠",
    color: "#ff424e",
    slug: "ngoi-lop-mai",
  },
  {
    id: 10,
    name: "Keo & Hóa Chất XD",
    icon: "🧪",
    color: "#0b74e5",
    slug: "keo-hoa-chat",
  },
  {
    id: 11,
    name: "Thiết Bị Vệ Sinh",
    icon: "🚿",
    color: "#0b74e5",
    slug: "thiet-bi-ve-sinh",
  },
  {
    id: 12,
    name: "Sắt & Thép Hình",
    icon: "⚙️",
    color: "#ff424e",
    slug: "sat-thep-hinh",
  },
  {
    id: 13,
    name: "Vật Liệu Hoàn Thiện",
    icon: "✨",
    color: "#ffa500",
    slug: "vat-lieu-hoan-thien",
  },
  {
    id: 14,
    name: "Máy Móc Xây Dựng",
    icon: "⚡",
    color: "#ff424e",
    slug: "may-moc-xay-dung",
  },
  {
    id: 15,
    name: "Cát, Đá, Sỏi",
    icon: "⛰️",
    color: "#0b74e5",
    slug: "cat-da-soi",
  },
  {
    id: 16,
    name: "Tấm Lợp & Cách Nhiệt",
    icon: "📋",
    color: "#0b74e5",
    slug: "tam-lop-cach-nhiet",
  },
  {
    id: 17,
    name: "Vật Liệu Trang Trí",
    icon: "🎭",
    color: "#ffa500",
    slug: "vat-lieu-trang-tri",
  },
  {
    id: 18,
    name: "Bảo Hộ Lao Động",
    icon: "🧺",
    color: "#ff424e",
    slug: "bao-ho-lao-dong",
  },
];

export const subCategories: Record<
  string,
  { id: number; name: string; slug: string }[]
> = {
  "xi-mang-vua": [
    { id: 1, name: "Xi Măng Portland", slug: "xi-mang-portland" },
    { id: 2, name: "Xi Măng Trộn Sẵn", slug: "xi-mang-tron-san" },
    { id: 3, name: "Vữa Xây Dựng", slug: "vua-xay-dung" },
    { id: 4, name: "Vữa Trát", slug: "vua-trat" },
    { id: 5, name: "Xi Măng Trắng", slug: "xi-mang-trang" },
    { id: 6, name: "Vữa Chống Thấm", slug: "vua-chong-tham" },
    { id: 7, name: "Bột Trét Tường", slug: "bot-tret-tuong" },
  ],
  "gach-xay-op-lat": [
    { id: 1, name: "Gạch Xây", slug: "gach-xay" },
    { id: 2, name: "Gạch Ốp Lát", slug: "gach-op-lat" },
    { id: 3, name: "Gạch Men", slug: "gach-men" },
    { id: 4, name: "Gạch Granite", slug: "gach-granite" },
    { id: 5, name: "Gạch Mosaic", slug: "gach-mosaic" },
    { id: 6, name: "Gạch Block", slug: "gach-block" },
  ],
  "son-chong-tham": [
    { id: 1, name: "Sơn Nội Thất", slug: "son-noi-that" },
    { id: 2, name: "Sơn Ngoại Thất", slug: "son-ngoai-that" },
    { id: 3, name: "Sơn Chống Thấm", slug: "son-chong-tham" },
    { id: 4, name: "Sơn Lót", slug: "son-lot" },
    { id: 5, name: "Sơn Dầu", slug: "son-dau" },
    { id: 6, name: "Sơn Epoxy", slug: "son-epoxy" },
  ],
  "thep-xay-dung": [
    { id: 1, name: "Thép Xây Dựng", slug: "thep-xay-dung" },
    { id: 2, name: "Thép Hình", slug: "thep-hinh" },
    { id: 3, name: "Thép Tấm", slug: "thep-tam" },
    { id: 4, name: "Thép Ống", slug: "thep-ong" },
    { id: 5, name: "Thép Không Gỉ", slug: "thep-khong-gi" },
  ],
  "ong-nuoc-phu-kien": [
    { id: 1, name: "Ống PVC", slug: "ong-pvc" },
    { id: 2, name: "Ống PPR", slug: "ong-ppr" },
    { id: 3, name: "Ống HDPE", slug: "ong-hdpe" },
    { id: 4, name: "Phụ Kiện Ống Nước", slug: "phu-kien-ong-nuoc" },
    { id: 5, name: "Van & Khóa", slug: "van-khoa" },
  ],
  "dien-den-chieu-sang": [
    { id: 1, name: "Đèn LED", slug: "den-led" },
    { id: 2, name: "Đèn Trang Trí", slug: "den-trang-tri" },
    { id: 3, name: "Công Tắc & Ổ Cắm", slug: "cong-tac-o-cam" },
    { id: 4, name: "Dây Điện", slug: "day-dien" },
    { id: 5, name: "Thiết Bị Điện", slug: "thiet-bi-dien" },
  ],
};
export const quickIcons = [
  {
    id: 1,
    name: "Xi Măng & Vữa",
    subtitle: "Giảm 15%",
    icon: "🏭",
    color: "bg-gradient-to-br from-blue-50 to-blue-100",
    badgeColor: "#ff424e",
    slug: "xi-mang-vua",
  },
  {
    id: 2,
    name: "Gạch Ốp Lát",
    subtitle: "Mới Về",
    icon: "🧱",
    color: "bg-gradient-to-br from-red-50 to-red-100",
    badgeColor: "#0b74e5",
    slug: "gach-xay-op-lat",
  },
  {
    id: 3,
    name: "Sơn & Chống Thấm",
    subtitle: "Hot Deal",
    icon: "🎨",
    color: "bg-gradient-to-br from-purple-50 to-purple-100",
    badgeColor: "#ff424e",
    slug: "son-chong-tham",
  },
  {
    id: 4,
    name: "Thép Xây Dựng",
    subtitle: "Giá Tốt",
    icon: "🔩",
    color: "bg-gradient-to-br from-gray-50 to-gray-100",
    badgeColor: "#0b74e5",
    slug: "thep-xay-dung",
  },
  {
    id: 5,
    name: "Ống Nước & Phụ Kiện",
    subtitle: "Giảm 20%",
    icon: "💧",
    color: "bg-gradient-to-br from-cyan-50 to-cyan-100",
    badgeColor: "#ff424e",
    slug: "ong-nuoc-phu-kien",
  },
  {
    id: 6,
    name: "Công Cụ Xây Dựng",
    subtitle: "Freeship",
    icon: "🔨",
    color: "bg-gradient-to-br from-orange-50 to-orange-100",
    badgeColor: "#0b74e5",
    slug: "cong-cu-xay-dung",
  },
  {
    id: 7,
    name: "Thiết Bị Điện ",
    subtitle: "Chính Hãng",
    icon: "💡",
    color: "bg-gradient-to-br from-yellow-50 to-yellow-100",
    badgeColor: "#ff424e",
    slug: "dien-den-chieu-sang",
  },
  {
    id: 8,
    name: "Ngói & Lợp Mái",
    subtitle: "Bảo Hành",
    icon: "🏠",
    color: "bg-gradient-to-br from-amber-50 to-amber-100",
    badgeColor: "#0b74e5",
    slug: "ngoi-lop-mai",
  },
  {
    id: 9,
    name: "Cát & Sỏi",
    subtitle: "Giao Nhanh",
    icon: "⛰️",
    color: "bg-gradient-to-br from-stone-50 to-stone-100",
    badgeColor: "#ff424e",
    slug: "cat-da-soi",
  },
  {
    id: 10,
    name: "Keo Dán & Hóa Chất ",
    subtitle: "Siêu Rẻ",
    icon: "🧪",
    color: "bg-gradient-to-br from-green-50 to-green-100",
    badgeColor: "#0b74e5",
    slug: "keo-hoa-chat",
  },
];
export const products = [
  {
    id: 1,
    name: "Xi măng Việt Nhật - Bao 50kg",
    slug: "xi-mang-viet-nhat-bao-50kg",
    price: 125000,
    originalPrice: 145000,
    discount: 14,
    rating: 4.8,
    reviewCount: 156,
    soldCount: 2340,
    image: "/cement2.jpg",
    images: ["/cement2.jpg", "/cement3.jpg", "/cement4.jpg", "/cement1.jpg"],
    category: "xi-mang-vua",
    brand: "Holcim",
    badges: ["CHÍNH HÃNG", "BÁN CHẠY"],
    nowDelivery: true,
    deliveryTime: "Giao trong ngày",
    description:
      "Xi măng Việt Nhật chính hãng Holcim, chất lượng cao, độ bền tốt, phù hợp mọi công trình xây dựng.",
    specifications: {
      weight: "50kg",
      origin: "Việt Nam",
      storage: "Bảo quản nơi khô ráo",
      expiry: "6 tháng kể từ ngày sản xuất",
    },
    features: [
      "Xi măng Việt Nhật chất lượng cao",
      "Độ bền cao, thời gian đông kết chuẩn",
      "Chính hãng Holcim, có tem chống giả",
      "Phù hợp xây dựng, đổ móng, trát tường",
      "Bao bì chắc chắn, dễ vận chuyển",
    ],
    seller: {
      name: "VietNhat Official Store",
      isOfficial: true,
      rating: 4.9,
      reviewCount: 523,
    },
  },
  {
    id: 2,
    name: "Gạch đá ốp lát Viglacera Eurotile Vọng Cát VOC G05",
    slug: "gach-granite-60x60-van-da-marble",
    price: 280000,
    originalPrice: 350000,
    discount: 20,
    rating: 4.9,
    reviewCount: 89,
    soldCount: 567,
    image: "/tiles4.webp",
    images: ["/tiles1.jpg", "/tiles2.jpg", "/tiles3.jpg", "/tiles4.jpg"],
    category: "gach-xay-op-lat",
    brand: "Viglacera",
    badges: ["FREESHIP", "CHÍNH HÃNG", "HOT"],
    nowDelivery: true,
    deliveryTime: "Giao trong 2 ngày",
    description:
      "Gạch granite cao cấp vân đá marble sang trọng, độ bóng cao, chống trầy xước tốt",
    specifications: {
      size: "60x60cm",
      thickness: "9.5mm",
      origin: "Việt Nam",
      packaging: "4 viên/thùng",
    },
    features: [
      "Vân đá marble tự nhiên cao cấp",
      "Độ bóng cao, chống trầy xước",
      "Kháng khuẩn, dễ vệ sinh",
      "Chống thấm nước tuyệt đối",
      "Bề mặt chống trơn trượt",
    ],
    seller: {
      name: "Viglacera Official Store",
      isOfficial: true,
      rating: 4.8,
      reviewCount: 320,
    },
  },
  {
    id: 3,
    name: "Enric Hoàn Hảo - Sơn ngoại thất Chống Loang Màu, Chống Sọc Đen 5L",
    slug: "son-ngoai-that-enric-hoan-hao-5l",
    price: 1450000,
    originalPrice: 1680000,
    discount: 14,
    rating: 4.9,
    reviewCount: 234,
    soldCount: 890,
    image: "/paint1.jpg",
    images: ["/paint1.jpg", "/paint2.jpg", "/paint3.jpg", "/paint4.jpg"],
    category: "son-chong-tham",
    brand: "Dulux",
    badges: ["CHÍNH HÃNG", "BÁN CHẠY"],
    nowDelivery: true,
    deliveryTime: "Giao trong ngày",
    description:
      "Sơn nội thất cao cấp Dulux Inspire, màu trắng tinh khiết, độ phủ tốt, không mùi",
    specifications: {
      volume: "18 lít",
      coverage: "90-100m²/thùng (2 lớp)",
      origin: "Việt Nam",
      finish: "Mờ nhẹ",
    },
    features: [
      "Công nghệ không mùi tiên tiến",
      "Độ phủ cao, tiết kiệm chi phí",
      "Màu sắc bền lâu, không phai",
      "Dễ thi công, khô nhanh",
      "An toàn cho sức khỏe",
    ],
    seller: {
      name: "Enric Paints Official",
      isOfficial: true,
      rating: 4.9,
      reviewCount: 450,
    },
  },
  {
    id: 4,
    name: "Thép Hòa Phát Phi 10 Việt Nhật - Cây 12m",
    slug: "thep-hoa-phat-phi-10-viet-nhat-cay-12m",
    price: 185000,
    originalPrice: 215000,
    discount: 14,
    rating: 4.7,
    reviewCount: 178,
    soldCount: 1234,
    image: "/thep1.jpg",
    images: [
      "/thep1.jpg",
      "/thep2.jpg",
      "/thep3.jpg",
      "/thep4.jpg",
    ],
    category: "thep-xay-dung",
    brand: "Việt Nhật",
    badges: ["CHÍNH HÃNG", "GIAO NHANH"],
    nowDelivery: false,
    deliveryTime: "Giao thứ 3, 14/01",
    description:
      "Thép xây dựng Việt Nhật phi 10, chất lượng cao, độ bền tốt, giá cạnh tranh",
    specifications: {
      diameter: "10mm",
      length: "12m",
      origin: "Việt Nam",
      standard: "TCVN 1651-1:2018",
    },
    features: [
      "Thép chất lượng cao Việt Nhật",
      "Độ bền kéo, chịu lực tốt",
      "Bề mặt gân đều, không gỉ",
      "Đạt tiêu chuẩn TCVN",
      "Giá cả cạnh tranh",
    ],
    seller: {
      name: "Thép Việt Nhật Official",
      isOfficial: true,
      rating: 4.7,
      reviewCount: 567,
    },
  },
  {
    id: 5,
    name: "Ống Nhựa PVC-U Hoa Sen - Dài 4m",
    slug: "ong-nhua-pvc-u-hoa-sen-d90-4m",
    price: 95000,
    originalPrice: 115000,
    discount: 17,
    rating: 4.8,
    reviewCount: 145,
    soldCount: 789,
    image: "/ongnhua1.jpg",
    images: [
      "/ongnhua1.jpg",
      "/ongnhua2.jpg",
      "/ongnhua3.jpg",
      "/ongnhua4.jpg",
    ],
    category: "ong-nuoc-phu-kien",
    brand: "Bình Minh",
    badges: ["CHÍNH HÃNG", "BÁN CHẠY"],
    nowDelivery: true,
    deliveryTime: "Giao trong 2 ngày",
    description:
      "Ống nhựa PVC Bình Minh phi 90, chất lượng cao, độ bền tốt, chống áp lực cao",
    specifications: {
      diameter: "90mm",
      length: "4m",
      origin: "Việt Nam",
      pressure: "10 bar",
    },
    features: [
      "PVC chất lượng cao, không độc hại",
      "Chịu áp lực cao, chống vỡ",
      "Bề mặt nhẵn, không ảnh hưởng nước",
      "Dễ lắp đặt, thi công",
      "Giá thành hợp lý",
    ],
    seller: {
      name: "Bình Minh Plastics",
      isOfficial: true,
      rating: 4.8,
      reviewCount: 423,
    },
  },
  {
    id: 6,
    name: "Đèn LED Ốp Trần Tròn 220/18W LN114 Philips",
    slug: "den-led-op-tran-220-18w-ln114-philips",
    price: 285000,
    originalPrice: 350000,
    discount: 19,
    rating: 4.9,
    reviewCount: 267,
    soldCount: 456,
    image: "/led1.webp",
    images: [
      "/led1.webp",
      "/led2.webp",
      "/led3.webp",
      "/led4.webp",
      "/led5.webp",
      "/led6.webp",
    ],
    category: "dien-den-chieu-sang",
    brand: "Philips",
    badges: ["CHÍNH HÃNG", "TIẾT KIỆM ĐIỆN"],
    nowDelivery: true,
    deliveryTime: "Giao trong ngày",
    description:
      "Đèn LED ốp trần Philips 24W, tiết kiệm điện, ánh sáng tự nhiên, tuổi thọ cao",
    specifications: {
      power: "24W",
      voltage: "220V",
      origin: "Trung Quốc",
      warranty: "24 tháng",
    },
    features: [
      "Công nghệ LED tiết kiệm điện",
      "Ánh sáng tự nhiên, không chói",
      "Tuổi thọ lên đến 25,000 giờ",
      "Thiết kế hiện đại, sang trọng",
      "Bảo hành chính hãng 2 năm",
    ],
    seller: {
      name: "Philips Lighting Official",
      isOfficial: true,
      rating: 4.9,
      reviewCount: 678,
    },
  },
  {
    id: 7,
    name: "Máy khoan Bosch GBM 10 RE (06014735K0)",
    slug: "may-khoan-bua-bosch-gsb-550",
    price: 890000,
    originalPrice: 1100000,
    discount: 19,
    rating: 4.8,
    reviewCount: 156,
    soldCount: 345,
    image: "/maykhoan1.jpg",
    images: ["/maykhoan1.jpg", "/maykhoan2.jpg", "/maykhoan3.jpg", "/maykhoan4.jpg"],
    category: "cong-cu-xay-dung",
    brand: "Bosch",
    badges: ["CHÍNH HÃNG", "BẢO HÀNH 12 THÁNG"],
    nowDelivery: true,
    deliveryTime: "Giao trong 2 ngày",
    description:
      "Máy khoan búa Bosch GSB 550, công suất 550W, khoan tường, gỗ, sắt hiệu quả",
    specifications: {
      power: "550W",
      chuck: "13mm",
      origin: "Malaysia",
      warranty: "12 tháng",
    },
    features: [
      "Động cơ 550W mạnh mẽ",
      "Khoan đa năng: tường, gỗ, sắt",
      "Thiết kế nhỏ gọn, dễ cầm",
      "Độ bền cao, chống quá tải",
      "Bảo hành chính hãng 12 tháng",
    ],
    seller: {
      name: "Bosch Power Tools",
      isOfficial: true,
      rating: 4.8,
      reviewCount: 389,
    },
  },
  {
    id: 8,
    name: "Cửa Nhựa Composite Phòng Ngủ 80x200cm",
    slug: "cua-nhua-composite-phong-ngu-80x200",
    price: 2850000,
    originalPrice: 3500000,
    discount: 19,
    rating: 4.7,
    reviewCount: 89,
    soldCount: 123,
    image: "/cua1.jpg",
    images: [
      "/cua1.jpg",
      "/cua2.jpg",
      "/cua3.jpg",

    ],
    category: "cua-cua-so",
    brand: "ABS Door",
    badges: ["CHÍNH HÃNG", "FREESHIP"],
    nowDelivery: false,
    deliveryTime: "Giao thứ 4, 15/01",
    description:
      "Cửa nhựa composite cao cấp, chống nước, chống mối mọt, cách âm, cách nhiệt tốt",
    specifications: {
      size: "80x200cm",
      thickness: "45mm",
      origin: "Việt Nam",
      warranty: "24 tháng",
    },
    features: [
      "Chất liệu composite cao cấp",
      "Chống nước, chống mối mọt",
      "Cách âm, cách nhiệt hiệu quả",
      "Màu sắc bền đẹp, không phai",
      "Lắp đặt đơn giản, bảo hành 2 năm",
    ],
    seller: {
      name: "ABS Door Official",
      isOfficial: true,
      rating: 4.7,
      reviewCount: 234,
    },
  },
];
export const featuredBrands = [
  {
    id: 1,
    name: "Xi Măng & Vữa",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Holcim - Lafarge",
    discount: "Giá giảm đến 15%",
  },
  {
    id: 2,
    name: "Gạch Ốp Lát",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Viglacera - Đồng Tâm",
    discount: "Giảm sâu 20%",
  },
  {
    id: 3,
    name: "Sơn & Chống Thấm",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Dulux - Jotun - Nippon",
    discount: "Khuyến mãi lớn",
  },
  {
    id: 4,
    name: "Thép Xây Dựng",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Việt Nhật - Hòa Phát",
    discount: "Giá tốt nhất",
  },
  {
    id: 5,
    name: "Ống Nước PVC",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Bình Minh - Tiền Phong",
    discount: "Ưu đãi 18%",
  },
  {
    id: 6,
    name: "Flash Sale Hôm Nay",
    logo: "/placeholder.svg?height=40&width=100",
    image: "/placeholder.svg?height=150&width=200",
    promo: "Deal Khủng Mỗi Ngày",
    discount: "Giảm đến 50%",
  },
];
export const internationalProducts = [
  {
    id: 1,
    name: "Sơn Nippon Premium All-In-1 - Thùng 5L (Nhật Bản)",
    price: 850000,
    originalPrice: 1050000,
    discount: 19,
    rating: 5,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in Japan",
    nowDelivery: true,
    badges: ["NHẬP KHẨU", "CHÍNH HÃNG"],
    seller: "Nippon Paint",
  },
  {
    id: 2,
    name: "Gạch Granite Porcelain Ý 60x120cm - Vân Đá Tự Nhiên",
    price: 580000,
    originalPrice: 750000,
    discount: 23,
    rating: 5,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in Italy",
    nowDelivery: false,
    deliveryTime: "Giao thứ 5, 16/01",
    badges: ["NHẬP KHẨU", "CAO CẤP"],
    seller: "Italy Tiles",
  },
  {
    id: 3,
    name: "Máy Khoan Pin Makita 18V DHP484 - Nhật Bản",
    price: 2850000,
    originalPrice: 3500000,
    discount: 19,
    rating: 4.9,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in Japan",
    nowDelivery: true,
    badges: ["NHẬP KHẨU", "CHÍNH HÃNG"],
    seller: "Makita Tools",
  },
  {
    id: 4,
    name: "Thiết Bị Vệ Sinh TOTO - Combo Bồn Cầu & Lavabo (Nhật)",
    price: 8500000,
    originalPrice: 10500000,
    discount: 19,
    rating: 5,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in Japan",
    nowDelivery: false,
    deliveryTime: "Giao thứ 6, 17/01",
    badges: ["NHẬP KHẨU", "CAO CẤP"],
    seller: "TOTO Vietnam",
  },
  {
    id: 5,
    name: "Keo Dán Gạch Weber (Pháp) - Bao 25kg",
    price: 185000,
    originalPrice: 230000,
    discount: 20,
    rating: 4.9,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in France",
    nowDelivery: true,
    deliveryTime: "Giao trong ngày",
    badges: ["NHẬP KHẨU", "CHÍNH HÃNG"],
    seller: "Weber Vietnam",
  },
  {
    id: 6,
    name: "Cửa Gỗ Composite Korea - Chống Nước Cao Cấp",
    price: 4850000,
    originalPrice: 6000000,
    discount: 19,
    rating: 4.8,
    image: "/placeholder.svg?height=200&width=200",
    origin: "Made in Korea",
    nowDelivery: false,
    deliveryTime: "Giao thứ 3, 14/01",
    badges: ["NHẬP KHẨU", "CAO CẤP"],
    seller: "Korea Door",
  },
];

export const reviews = [
  {
    id: 1,
    userId: "MT",
    userName: "Nguyễn Thế Minh Thiện",
    memberYears: 5,
    reviewCount: 18,
    helpfulCount: 9,
    rating: 5,
    title: "Xi măng chất lượng tốt",
    content:
      "Xi măng chính hãng, bê tông rất chắc, thời gian đông kết nhanh. Đóng gói cẩn thận, không bị rách. Giá cả hợp lý hơn thị trường. Sẽ đặt thêm ở lần sau.",
    isPurchased: true,
    variant: "50kg",
    date: "2 tuần trước",
    usageDays: 14,
    images: [
      "/cement1.jpg",
      "/cement2.jpg",
      "/cement3.jpg",
    ],
    likes: 12,
    comments: 2,
  },
  {
    id: 2,
    userId: "MT",
    userName: "Đậu Minh Tuấn",
    memberYears: 3,
    reviewCount: 8,
    helpfulCount: 5,
    rating: 5,
    title: "Giao hàng nhanh, sản phẩm tốt",
    content:
      "Lần đầu mua vật liệu online, ban đầu hơi lo lắng nhưng khi nhận hàng thì rất hài lòng. Xi măng chính hãng, có tem chống giả. Giao hàng nhanh, nhân viên nhiệt tình.",
    isPurchased: true,
    variant: "50kg",
    date: "1 tháng trước",
    usageDays: 30,
    images: ["/led1.webp", "/led2.webp", "/led3.webp", "/led4.webp"],
    likes: 8,
    comments: 1,
  },
];

export const formatPrice = (price: number) => {
  return new Intl.NumberFormat("vi-VN").format(price) + "đ";
};

export const banners = [
  {
    id: 1,
    title: "VẬT LIỆU XÂY DỰNG",
    subtitle: "CHẤT LƯỢNG CAO - GIÁ TỐT",
    image: "/banner1.png",
    link: "/category/xi-mang-vua",
    badges: ["GIẢM ĐẾN 30%", "GIAO NHANH TRONG NGÀY", "FREESHIP"],
  },
  {
    id: 2,
    title: "Xi măng chính hãng",
    subtitle: "Giá tốt nhất",
    image: "/banner2.png",
    link: "/category/xi-mang-vua",
    badges: ["Giảm 15%", "Bảo hành 6 tháng"],
    isSecondary: true,
  },
];
